### ISSUE TITLE
If there's no .session file, try get the session from aoc-session

### ISSUE THREAD

**Issue by JohnScience** [sncxyz/aocli#5]
Hi, I'm the author of [`aoc-session`](https://crates.io/crates/aoc-session) crate. I figured your crate could benefit from using it. See [`aoc_session::aoc_session`](https://docs.rs/aoc-session/0.1.0/aoc_session/fn.aoc_session.html).

It has many (~200) dependencies inherited from [`rookie`](https://crates.io/crates/rookie) but that's the price for support of many browsers and platforms:

* Chrome: Linux, MacOS, Windows
* Firefox: Linux, MacOS, Windows
* LibreWolf: Linux, MacOS, Windows
* Opera: Linux, MacOS, Windows
* Opera GX: MacOS, Windows
* Edge: Linux, MacOS, Windows
* Internet Explorer: Windows
* Chromium: Linux, MacOS, Windows
* Brave: Linux, MacOS, Windows
* Vivaldi: Linux, MacOS, Windows
* Safari: MacOS

If you're concerned about long compile times, you can consider becoming [`cargo-binstall`](https://crates.io/crates/cargo-binstall)-compatible.

**Comment by sncxyz** [comment]
Hi, thanks for the suggestion, but I've decided against using automatic cookie acquisition because I was advised that people might not want a program digging around their browser cookies.
