### ISSUE TITLE
Please provide an example of a `.session` file

### ISSUE THREAD

**Issue by JohnScience** [sncxyz/aocli#6]
It would be awesome to have a `.example.session` to see the format of a cookie. As far as I understand, only `session=<...>` is the necessary part of a cookie (as I explored in [my presentation](https://docs.google.com/presentation/d/1v5IM6GbMgvC2EVPQnJ1-adwQONMmLOWmDeGGE6Ehx-U/edit?usp=sharing)) but for some reason `aoc-session > .session` was not sufficient to make `aoc get 2022 1` work.

First attempt of `.session`:

```
session=53616c7465645f5f286128b614b18e3d5a906611b3bac6740671d5e461a7ab0d2be049fb7363eadb2e07ecfe51b600927ddd29b2311ea418ce366e8b9cf98dbb

```

(unlike here, I used my real `session` value).

Second attempt of `.session`:

```
session=53616c7465645f5f286128b614b18e3d5a906611b3bac6740671d5e461a7ab0d2be049fb7363eadb2e07ecfe51b600927ddd29b2311ea418ce366e8b9cf98dbb
```

Third attempt of `.session`:

```
Cookie: session=53616c7465645f5f286128b614b18e3d5a906611b3bac6740671d5e461a7ab0d2be049fb7363eadb2e07ecfe51b600927ddd29b2311ea418ce366e8b9cf98dbb

```

Fourth attempt of `.session` (successful):

```
_ga=GA1.2.1481191691.1701307337; _gid=GA1.2.2089724069.1701307337; session=53616c7465645f5f286128b614b18e3d5a906611b3bac6740671d5e461a7ab0d2be049fb7363eadb2e07ecfe51b600927ddd29b2311ea418ce366e8b9cf98dbb; _ga_MHSNPJKWC7=GS1.2.1701383119.5.1.1701383528.0.0.0

```

(note: after reading [the source code](https://github.com/sncxyz/aocli/blob/d2008e1e207414877882e128534aba4593a09d6a/src/action.rs#L547), I wonder why this even works)

Fifth attempt of `.session` (successful):

```
53616c7465645f5f286128b614b18e3d5a906611b3bac6740671d5e461a7ab0d2be049fb7363eadb2e07ecfe51b600927ddd29b2311ea418ce366e8b9cf98dbb

```

~~I don't understand why I can `curl` the problem while supplying only `session` but `aoc` also requires Google Analytics cookies. Could `curl` be treated differently due to `User-Agent` header?~~

**Comment by JohnScience** [comment]
Opened a PR: https://github.com/sncxyz/aocli/pull/7

**Comment by sncxyz** [comment]
I've added a note in the README that the .session file should contain the cookie with or without the `session=` header, which should suffice.
