### ISSUE TITLE
This project does not seem to work as expected with a workspace

### ISSUE THREAD

**Issue by hmvp** [sncxyz/aocli#8]
I am running vscode with rust-analyser plugin and that kind of expects an cargo workspace at the project root. However if you add that, the answer is always 0 since it seems to run the wrong binary....

As a workaround I used the rust-analyser setting `rust-analyzer.linkedProjects`...

Both a workspace (which is the best option IMHO) and this setting however require me to add all "days" to a list.. Would be nice if that was manager by the cli...

**Comment by sncxyz** [comment]
I've just had individual year or day directories open in VSC so far. I was aware having the project root open didn't detect the workspace properly, but wasn't aware there was a fix for it, let alone a way for the CLI to apply it automatically. Definitely looks like something that should be added!

I'm not sure what you mean by running the wrong binary though.

**Comment by hmvp** [comment]
So adding a Cargo.toml in the root with contest similar to

```toml
[workspace]
members = [
  "2023/01",
  "2023/02",
```

Should fix vscode picking up all the individual days. That is something `aoc new` could manage

However when I do that manually it fails because the day binary lives in the target dir of the workspace when useing workspaces. I now get an `error: No such file or directory (os error 2)` error. Before I must not have cleaned an old attempt and there was an initial version of the binary in the day target dir that always return 0

**Comment by hmvp** [comment]
Hmm another issue is that if you have multiple years, you get the error:

```
error: two packages named `day-01` in this workspace:
- /2021/01/Cargo.toml
- /2023/01/Cargo.toml
```

**Comment by sncxyz** [comment]
The latter issue can be fixed by just naming the day crates according to their year too. I'm still not sure I understand the former issue, though. When you set the members of the workspace manually, what is it that fails? Is it because it requires rearranging the file structure? I'm not familiar with workspaces.

**Comment by hmvp** [comment]
With workspaces there is one global target folder instead of a target folder per sub project. So to make it work for me I needed to change "target" to "../../target" in https://github.com/sncxyz/aocli/blob/544d6b467e71bf937ac0b6d57a43387ad7d95b6a/src/run.rs#L43 

And indeed the other issue was fixed by changing the runner to deal with project names like "year-2023-day-01" instead of "day-01"

**Comment by sncxyz** [comment]
I could add a setting for aocli so that it knows whether to use a workspace or not, and finds the target directory accordingly. Or I could make the `cargo build` command build into a directory within the day itself, if that's possible?

**Comment by hmvp** [comment]
Not sure about changing cargo build, I expect the former to be easier...

**Comment by sncxyz** [comment]
is [this option](https://doc.rust-lang.org/cargo/commands/cargo-build.html#output-options) not sufficient?

**Comment by sncxyz** [comment]
Maybe it breaks the workspace stuff. But if not, this option could allow it to work both with and without workspaces without a setting.

**Comment by hmvp** [comment]
Oh that will probably work. The upside of using workspaces might be (not entirely sure about that) that it might reuse dependencies over sub projects so it does not have to compile them. Not sure if that option will hinder that...

**Comment by sncxyz** [comment]
Good point, I'll take that into consideration. I won't look into it more today, but will within the next few days. Thanks for the ideas! If you think of anything in the meantime, feel free to post it here.

**Comment by sncxyz** [comment]
(I suppose it will need a setting if `new` is going to automatically handle the workspace members...)

**Comment by sncxyz** [comment]
Oh, and of course a perfectly viable approach is to just adapt it to create a workspace with `aoc init`, and fully switch to using those. This seems like a good idea, especially if workspaces do help with compile times.

**Comment by sncxyz** [comment]
Cargo Workspaces do share dependencies when compiling, and it was pretty easy to implement all the changes, so I've fully swapped to using them. Migrating to the new system will require quite a bit of work... hopefully an explanation in the Release notes should suffice.

**Comment by sncxyz** [comment]
@hmvp [new release](https://github.com/sncxyz/aocli/releases/tag/v0.0.9) :)

**Comment by hmvp** [comment]
Cool! Thanks!
