### ISSUE TITLE
Make use of clap to parse cli arguments and commands

### ISSUE THREAD

**Issue by LMH01** [sncxyz/aocli#9]
I think it would be a nice idea to use [cli](https://docs.rs/clap/latest/clap/) to parse the cli arguments.

This would for example create a nice help page directly in the terminal instead of opening the repository site.

I could probably implement it myself and create a pull request if you like (but I'm not sure when I have time for that).

**Comment by sncxyz** [comment]
I considered using clap to begin with, but chose not to use it for a couple of reasons:
- Stylistic: I wanted error messages to have a consistent style, whether they're CLI-related or not
- Control: I wanted full control over how the CLI works and looks
- Unusual CLI: aocli uses optional positional arguments and has no flags, as well as split commands like `run days`, which would have been difficult at the least to implement with clap

In addition, swapping over to clap now would require reworking the entire CLI which would take a lot of effort and sacrifice the consistency in style. However, I have been intending to add help messages within the CLI at some point, and added a link to the README as a temporary solution.

Therefore I think it would be better to implement help messages into the existing CLI, which would require far less effort and retain the current style and control.

**Comment by LMH01** [comment]
Thanks for your reply, I think that you are right.

Yeah I like the idea of a help page that is "manually" written.

You can feel free to close this issue.
